// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVEZJ_I9TNwivxF-7KVejXRzoEqPZuSoU',
    appId: '1:182335270449:android:c71548c1c8f1df7ce9ef10',
    messagingSenderId: '182335270449',
    projectId: 'alansabwetlandapplication',
    storageBucket: 'alansabwetlandapplication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANSP5TiwRkaMvKnsnyPOVcky1-cMpie5U',
    appId: '1:182335270449:ios:82d6b2a7eb38531de9ef10',
    messagingSenderId: '182335270449',
    projectId: 'alansabwetlandapplication',
    storageBucket: 'alansabwetlandapplication.appspot.com',
    androidClientId: '182335270449-ku7j88pef7fc1pqolo2lo1voi84p8vpf.apps.googleusercontent.com',
    iosClientId: '182335270449-k6p1e6oe3do9a4rocj8avtb5s66jn1al.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
